name: Terraform Apply (Controlled)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev or prod)"
        required: true
        type: choice
        options:
          - dev
          - prod
        default: dev

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      TF_VAR_hosted_zone_id: ${{ vars.TF_VAR_HOSTED_ZONE_ID }}
      TF_VAR_site_bucket_name: ${{ vars.TF_VAR_SITE_BUCKET_NAME }}

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Terraform Environment
        uses: ./.github/actions/terraform-setup
        with:
          working-directory: terraform/environments/${{ github.event.inputs.environment }}
          terraform-version: "1.15.3"
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront for environment: ${{ github.event.inputs.environment }}"

          DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)

          aws cloudfront create-invalidation \
            --distribution-id "$DISTRIBUTION_ID" \
            --paths "/index.html" "/app.js" "/assets/*"
